services: # Define todos os serviços da aplicação
  web: # Serviço da sua API FastAPI
    build: . # Constrói a imagem usando o Dockerfile da pasta atual

    ports:
      - "8000:8000" # Porta do PC -> porta do container

    env_file:
      - .env

    volumes:
      - .:/app:rw # Sincroniza arquivos (útil para desenvolvimento)

    depends_on:
      - db # Garante que o banco suba antes da API

    command: > # Comando executado ao iniciar o container
      sh -c "
      uv sync --all-groups &&
      uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    networks:
      - pokeapi_network # Conecta à rede personalizada

    # Atualiza o pip
    # Instala dependências
    # Inicia o FastAPI com reload automático

  db: # Serviço do banco de dados PostgreSQL
    image: postgres:18 # Usa imagem oficial do PostgreSQL

    env_file:
      - .env # Carrega variáveis de ambiente do arquivo db.env
    ports:
      - "5432:5432" # Porta padrão do PostgreSQL
    networks:
      - pokeapi_network # Conecta à rede personalizada
volumes:
  db_data: # Volume para não perder dados ao parar o container

networks:
  pokeapi_network: # Rede personalizada para comunicação entre serviços
    driver: bridge
